# Generated by Django 4.2.3 on 2024-05-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings_comments_closedlistings_bids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosedListings',
        ),
    ]
