# Generated by Django 4.2.3 on 2024-06-16 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_followers_delete_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posting', to=settings.AUTH_USER_MODEL),
        ),
    ]
