# Generated by Django 4.2.3 on 2024-06-21 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_posts_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followerusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
